apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: csbuhcc50-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: csbuhcc50-go 
  name: csbuhcc50-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: csbuhcc50-go 
